apiVersion: v1
kind: Service
metadata:
  name: ticket-ia-service
spec:
  type: NodePort
  selector:
    app: ticket-ia
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8005
      nodePort: 30080
